steps:
  # ビルドステップ: Dockerイメージをビルドして Container Registry にプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/weather-notion-api:$COMMIT_SHA', '.']
  
  # イメージをプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/weather-notion-api:$COMMIT_SHA']
  
  # デプロイステップ: Cloud Run にデプロイ
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'weather-notion-api'
      - '--image=gcr.io/$PROJECT_ID/weather-notion-api:$COMMIT_SHA'
      - '--region=asia-northeast1'  # 東京リージョン
      - '--platform=managed'
      - '--allow-unauthenticated'  # 公開APIにする場合。認証が必要な場合は削除
      - '--memory=512Mi'
      - '--timeout=900s'           # タイムアウト設定（最大15分）
      - '--cpu=1'
      - '--set-env-vars=^:^'       # 環境変数はCloud Runのコンソールで設定

# タイムアウト設定（デフォルトは10分）
timeout: '1800s'

# イメージの保存
images:
  - 'gcr.io/$PROJECT_ID/weather-notion-api:$COMMIT_SHA' 
